# This is the Makefile for Robot Game (version 1)
# To use, at the prompt, type:
#
#	make new		# This will safely remove old stuff, and
#				# will then "make" again.
#
#	make clean		# cleans up directory

all:
	javac *.java

clean:
	rm -f *.class

run:
	java Robot