# This is the Makefile for Robot Game (version 2)
# To use, at the prompt, type:
#
#	make 		    # This will safely remove old stuff, and
#				    # will then "make" again.
#
#	make clean		# cleans up directory
#
#   make run		# run the program

all:
	javac *.java

clean:
	rm -f *.class

run:
	java Robot